apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: items-app
  namespace: items-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: items.local     # Change to your domain if you have one
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: items-app
                port:
                  number: 80
